# Exploratory Data Analysis of Aviation Accident Data


## Description

This Jupyter Notebook performs an exploratory data analysis (EDA) on a dataset containing information about aviation accidents. The dataset includes details about different aviation accidents, such as accident type, location, date, and factors contributing to the accidents.

The purpose of this analysis is to gain insights into the dataset and answer several key questions:

1. What are the most common causes of accidents among Part 121 air carriers?
2. Are there any seasonal or time-related patterns in accidents?
3. How has the safety record of Part 121 air carriers evolved over the years?
4. Are there any correlations between specific factors (e.g., weather conditions, aircraft types) and accident severity?

By exploring and visualizing the data, the aim is to provide a better understanding of aviation accidents and identify trends and patterns that may be useful for improving aviation safety.

---

**Note**: This notebook is for educational and analytical purposes only. It does not cover any specific incident or accident investigation.

# Imports
## Libraries

In [1]:
# Standard Library Imports
import os
import sys
from datetime import datetime

# Third-Party Library Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Custom function import
from scripts.load_data import load_data

# Print a timestamp to indicate when the imports were executed
print(f"Imports executed at {datetime.now()}")

Imports executed at 2023-12-30 12:36:26.890801

## Data

Please see [Data Loading](http://localhost:8888/notebooks/MyGitRepo/NTSB-Aviation-Investigation-Analysis/code/scripts/load_data.ipynb) for more information on the data loading process

In [2]:
# Load all tables
loaded_data = load_data(load_all=True)

#Print a timestamp to indicate when the import was executed
print(f"Data Import Completed at {datetime.now()}")

Data Import Completed at 2023-12-30 12:36:38.558547

In [3]:
loaded_data

{'narratives':                 ev_id  Aircraft_Key  \
 0      20080211X00175             1
 1      20080107X00026             1
 2      20080107X00026             2
 3      20080109X00036             1
 4      20080107X00027             1
 ...               ...           ...
 25243  20231114193384             1
 25244  20231114193385             1
 25245  20231114193387             1
 25246  20231115193389             1
 25247  20231120193406             1

                                            narr_complete
 0                                              import
 1      On January 1, 2008, about 1430 Pacific standar...
 2      On January 1, 2008, about 1430 Pacific standar...
 3      The private pilot was conducting a touch-and-g...
 4      On January 3, 2008, approximately 0225 central...
 ...                                                  ...
 25243  On November 13, 2023, about 0800 Pacific stand...
 25244  On November 14, 2023, about 1008 Mountain stan...
 25245  On November 14, 2023, at 1409 eastern standard...
 25246  On November 15, 2023, about 1040 central stand...
 25247  On November 17, 2023, about 1708 eastern stand...

 [25248 rows x 3 columns],
 'country':     COUNTRY_CODE    COUNTRY_NAME
 0            USA   United States
 1             AF     Afghanistan
 2             AL         Albania
 3             AG         Algeria
 4             AQ  American Samoa
 ..           ...             ...
 254           WS   Western Samoa
 255           YM           Yemen
 256           CG           Zaire
 257           ZA          Zambia
 258           ZI        Zimbabwe

 [259 rows x 2 columns],
 'event_seq':                 ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
 0      20080107X00026             1              1           550250
 1      20080107X00026             2              1           350250
 2      20080109X00036             1              1           551230
 3      20080109X00036             1              2           550300
 4      20080107X00027             1              1           153081
 ...               ...           ...            ...              ...
 57664  20231129193447             1              1           552096
 57665  20231129193448             1              1           552490
 57666  20231129193449             1              1           552230
 57667  20231129193451             1              1           452470
 57668  20231201193459             1              1           250470

                                   Occurrence_Description  phase_no  \
 0                               Landing Midair collision       550
 1                         Initial climb Midair collision       350
 2      Landing-flare/touchdown Loss of control on ground       551
 3                               Landing Runway excursion       550
 4      Standing-engine(s) operating AC/prop/rotor con...       153
 ...                                                  ...       ...
 57664           Landing-landing roll Nose over/nose down       552
 57665  Landing-landing roll Collision during takeoff/...       552
 57666     Landing-landing roll Loss of control on ground       552
 57667  Maneuvering-low-alt flying Collision with terr...       452
 57668           Taxi Collision with terr/obj (non-CFIT)        250

        eventsoe_no  Defining_ev            lchg_date  lchg_userid
 0              250         True  2020-09-25 18:05:31          NaN
 1              250         True  2020-09-25 18:05:31          NaN
 2              230         True  2020-09-25 18:05:31          NaN
 3              300        False  2020-09-25 18:05:31          NaN
 4               81         True  2020-09-25 18:04:02          NaN
 ...            ...          ...                  ...          ...
 57664           96         True  2023-12-01 18:34:35          NaN
 57665          490         True  2023-11-29 20:38:38          NaN
 57666          230         True  2023-11-30 16:34:41          NaN
 57667          470         True  2023-11-29 23:57:06          NaN
 57668          470         True  2023-12-01 20:09:01          NaN

 [57669 rows x 10 columns],
 'findings':                 ev_id  Aircraft_Key  finding_no  finding_code  \
 0      20080107X00026             1           1     204151045
 1      20080107X00026             2           1     204151044
 2      20080109X00036             1           1     303404099
 3      20080109X00036             1           2     106202020
 4      20080107X00027             1           1     303602099
 ...               ...           ...         ...           ...
 63063  20231018193262             1           9     303402587
 63064  20231025193303             1           5     204151046
 63065  20231025193303             1           3     202154540
 63066  20231025193303             1           4     302202587
 63067  20231026193309             1           1     302204581

                                      finding_description  category_no  \
 0      Personnel issues-Action/decision-Info processi...            2
 1      Personnel issues-Action/decision-Info processi...            2
 2      Environmental issues-Conditions/weather/phenom...            3
 3      Aircraft-Aircraft oper/perf/capability-Perform...            1
 4      Environmental issues-Conditions/weather/phenom...            3
 ...                                                  ...          ...
 63063  Environmental issues-Conditions/weather/phenom...            3
 63064  Personnel issues-Action/decision-Info processi...            2
 63065  Personnel issues-Psychological-Attention/monit...            2
 63066  Environmental issues-Physical environment-Obje...            3
 63067  Environmental issues-Physical environment-Obje...            3

        subcategory_no  section_no  subsection_no  modifier_no Cause_Factor  \
 0                   4          15             10           45            C
 1                   4          15             10           44            C
 2                   3          40             40           99            F
 3                   6          20             20           20            C
 4                   3          60             20           99            F
 ...               ...         ...            ...          ...          ...
 63063               3          40             25           87          NaN
 63064               4          15             10           46          NaN
 63065               2          15             45           40          NaN
 63066               2          20             25           87          NaN
 63067               2          20             45           81          NaN

                  lchg_date lchg_userid
 0      2020-09-25 18:05:31         NaN
 1      2020-09-25 18:05:31         NaN
 2      2020-09-25 18:05:31         NaN
 3      2020-09-25 18:05:31         NaN
 4      2020-09-25 18:04:02         NaN
 ...                    ...         ...
 63063  2023-11-16 19:00:05      linj-i
 63064  2023-11-16 19:00:05        coln
 63065  2023-11-16 19:00:05        coln
 63066  2023-11-16 19:00:05        coln
 63067  2023-11-16 19:00:05      linj-i

 [63068 rows x 13 columns],
 'flight_crew':                 ev_id  Aircraft_Key  crew_no crew_category  crew_age crew_sex  \
 0      20080107X00026             1        1           PLT      56.0        M
 1      20080107X00026             2        1           PLT      70.0        M
 2      20080109X00036             1        1           PLT      54.0        F
 3      20080107X00027             1        1           PLT      59.0        M
 4      20080115X00051             1        1          DSTU      36.0        M
 ...               ...           ...      ...           ...       ...      ...
 27353  20231018193262             1        2          PRPS      78.0        M
 27354  20231025193303             1        1          FLTI      81.0        M
 27355  20231025193303             1        2          DSTU      62.0        M
 27356  20231026193309             1        1           PLT      23.0        M
 27357  20231026193309             1        2          DSTU      18.0        M

            crew_city crew_res_state crew_res_country med_certf  ...  \
 0             Novato             CA              USA       CL3  ...
 1            Pioneer             CA              USA       CL3  ...
 2           Gonzales             TX              USA       CL3  ...
 3             Conroe             TX              USA       CL2  ...
 4           Loveland             CO              USA       CL3  ...
 ...              ...            ...              ...       ...  ...
 27353        Windsor             CO              USA       NaN  ...
 27354      Lexington             SC              USA       CL2  ...
 27355      Lexington             SC              USA       CL3  ...
 27356           Waco             TX              USA       CL1  ...
 27357  New Braunfels             TX              USA       CL1  ...

       lchg_userid seat_occ_row  infl_rest_inst infl_rest_depl  \
 0             NaN          NaN             NaN            NaN
 1             NaN          NaN             NaN            NaN
 2             NaN          NaN             NaN            NaN
 3             NaN          NaN             NaN            NaN
 4             NaN          NaN             NaN            NaN
 ...           ...          ...             ...            ...
 27353      linj-i          NaN               N            NaN
 27354        coln          NaN               U            NaN
 27355        coln          NaN               U            NaN
 27356      linj-i          NaN               N            NaN
 27357      linj-i          NaN               N            NaN

        child_restraint     med_crtf_limit mr_faa_med_certf pilot_flying  \
 0                  NaN                NaN              NaN        False
 1                  NaN                NaN              NaN        False
 2                  NaN                NaN              NaN        False
 3                  NaN                NaN              NaN        False
 4                  NaN                NaN              NaN        False
 ...                ...                ...              ...          ...
 27353              NaN                NaN              NaN        False
 27354              NaN  Corrective Lenses              NaN        False
 27355              NaN  Corrective Lenses              NaN         True
 27356              NaN                NaN              NaN         True
 27357              NaN                NaN              NaN         True

       available_restraint  restraint_used
 0                     NaN             NaN
 1                     NaN             NaN
 2                     NaN             NaN
 3                     NaN             NaN
 4                     NaN             NaN
 ...                   ...             ...
 27353                   4               4
 27354                   L               L
 27355                   L               L
 27356                   3               3
 27357                   3               3

 [27358 rows x 33 columns],
 'ntsb_admin':                 ev_id rec_stat        approval_date lchg_userid  \
 0      20080211X00175        F  2008-02-11 00:00:00      gibs-i
 1      20080107X00026        B  2008-04-30 00:00:00         NaN
 2      20080109X00036        B  2008-01-31 00:00:00         NaN
 3      20080107X00027        B  2008-03-31 00:00:00         NaN
 4      20080115X00051        B  2008-01-31 00:00:00         NaN
 ...               ...      ...                  ...         ...
 26595  20231129193447        P                  NaN        nixa
 26596  20231129193448        P                  NaN        bakd
 26597  20231129193449      NaN                  NaN      stes-i
 26598  20231129193451      NaN                  NaN        hodm
 26599  20231201193459      NaN                  NaN        band

                  lchg_date
 0      2023-08-03 13:29:08
 1      2020-09-25 18:05:31
 2      2020-09-25 18:05:31
 3      2020-09-25 18:04:02
 4      2020-09-25 18:06:16
 ...                    ...
 26595  2023-12-01 18:34:35
 26596  2023-11-29 20:38:38
 26597  2023-11-30 16:34:41
 26598  2023-11-29 23:57:06
 26599  2023-12-01 20:09:01

 [26600 rows x 5 columns],
 'aircraft':                 ev_id  Aircraft_Key regis_no      ntsb_no acft_missing  \
 0      20080211X00175             1   N530NA   DFW08RA039            N
 1      20080107X00026             1   N8037W  SEA08LA057A            N
 2      20080107X00026             2    N15EX  SEA08LA057B            N
 3      20080109X00036             1   N579RM   DFW08CA054            N
 4      20080107X00027             1    N398J   DFW08LA055            N
 ...               ...           ...      ...          ...          ...
 27013  20231129193447             1   N9991N   WPR24LA043            N
 27014  20231129193448             1    N82TK   WPR24LA044            N
 27015  20231129193449             1   N170HT   WPR24LA045            N
 27016  20231129193451             1   N745MB   CEN24FA049            N
 27017  20231201193459             1   N494HA   DCA24LA034            N

       far_part flt_plan_filed flight_plan_activated damage acft_fire  ...  \
 0         NUSN            NaN                   NaN   SUBS       NaN  ...
 1          091           NONE                   NaN   MINR      NONE  ...
 2          091           NONE                   NaN   SUBS      NONE  ...
 3          091           NONE                     N   SUBS      NONE  ...
 4          091            IFR                     Y    NaN      NONE  ...
 ...        ...            ...                   ...    ...       ...  ...
 27013      091            NaN                   NaN   SUBS      NONE  ...
 27014      091           NONE                     N   SUBS      NONE  ...
 27015      091            NaN                   NaN    NaN       NaN  ...
 27016      NaN            NaN                   NaN    NaN       NaN  ...
 27017      121            NaN                   NaN    NaN       NaN  ...

       acft_year fuel_on_board commercial_space_flight unmanned  \
 0           NaN           NaN                   False    False
 1           NaN           NaN                   False    False
 2           NaN           NaN                   False    False
 3           NaN           NaN                   False    False
 4           NaN           NaN                   False    False
 ...         ...           ...                     ...      ...
 27013    1975.0           NaN                   False    False
 27014    2017.0           NaN                   False    False
 27015       NaN           NaN                   False    False
 27016       NaN           NaN                   False    False
 27017       NaN           NaN                   False    False

       ifr_equipped_cert  elt_mounted_aircraft elt_connected_antenna  \
 0                 False                 False                 False
 1                 False                 False                 False
 2                 False                 False                 False
 3                 False                 False                 False
 4                 False                 False                 False
 ...                 ...                   ...                   ...
 27013             False                 False                 False
 27014             False                 False                 False
 27015             False                 False                 False
 27016             False                 False                 False
 27017             False                 False                 False

        elt_manufacturer elt_model  elt_reason_other
 0                   NaN       NaN               NaN
 1                   NaN       NaN               NaN
 2                   NaN       NaN               NaN
 3                   NaN       NaN               NaN
 4                   NaN       NaN               NaN
 ...                 ...       ...               ...
 27013               NaN       NaN               NaN
 27014               NaN       NaN               NaN
 27015               NaN       NaN               NaN
 27016               NaN       NaN               NaN
 27017               NaN       NaN               NaN

 [27018 rows x 93 columns],
 'ct_iaids':                   ct_name code_iaids                           meaning   seq  \
 0               ct_office        CEN                    Central Region   NaN
 1               ct_office        CHI     North Central Regional Office   NaN
 2               ct_office        DCA               Major Investigation   NaN
 3               ct_office        DEN  Central Mountain Regional Office   NaN
 4               ct_office        DFW     South Central Regional Office   NaN
 ..                    ...        ...                               ...   ...
 950  ct_load_desc                PAX                        Passengers   2.0
 951  ct_load_desc               TOWB                     Towing Banner   5.0
 952  ct_load_desc               TOWG                     Towing Glider   4.0
 953  ct_load_desc                UNK                           Unknown   0.0
 954  ct_load_desc               UNKA                        Unknown/NA  12.0

     ntsb_type ntsb_code avn_code ntsb_codes_more  not_for_ntsb_use  eADMS_use  \
 0         NaN       NaN      NaN             NaN             False       True
 1         NaN       NaN      NaN             NaN             False       True
 2         NaN       NaN      NaN             NaN             False       True
 3         NaN       NaN      NaN             NaN             False       True
 4         NaN       NaN      NaN             NaN             False       True
 ..        ...       ...      ...             ...               ...        ...
 950         N        02                      NaN             False      False
 951         N        05                      NaN             False      False
 952         N        04                      NaN             False      False
 953         N        00                      NaN             False      False
 954         N        12                      NaN             False      False

                       notes
 0                       NaN
 1                       NaN
 2                       NaN
 3                       NaN
 4                       NaN
 ..                      ...
 950  Keep for archived data
 951  Keep for archived data
 952  Keep for archived data
 953  Keep for archived data
 954  Keep for archived data

 [955 rows x 11 columns],
 'ct_seqevt':        code                                            meaning
 0       100                                    ABRUPT MANEUVER
 1       110                    ALTITUDE DEVIATION,UNCONTROLLED
 2       120                                        CARGO SHIFT
 3       130      AIRFRAME/COMPONENT/SYSTEM FAILURE/MALFUNCTION
 4       131                      PROPELLER FAILURE/MALFUNCTION
 ...     ...                                                ...
 2219  92400     INADEQUATE CERTIFICATION/APPROVAL,MANUFACTURER
 2220  93000                  INADEQUATE SUBSTANTIATION PROCESS
 2221  93100  INADEQ METHOD OF COMPLIANCE DETERMINATION RCRD...
 2222  93200    INADEQUATE SUBSTANTIATION PROCESS,INSUFF REVIEW
 2223  93300  INADEQ SUBSTANTIATION PROCESS,INADEQ DOCUMENTA...

 [2224 rows x 2 columns],
 'dt_flight_crew':                  ev_id  Aircraft_Key  crew_no            col_name  code  \
 0       20080107X00026             1        1      crew_cert_code   PRI
 1       20080107X00026             1        1     crew_rat_airpln   SEL
 2       20080107X00026             1        1     crew_rat_airpln   SES
 3       20080107X00026             1        1  crew_rat_instruct0  NONE
 4       20080107X00026             1        1   crew_rat_instrum0  NONE
 ...                ...           ...      ...                 ...   ...

Error Handling: Implement try-except blocks to handle potential errors during data loading. This could include handling file not found errors, incorrect format issues, or network-related problems when fetching from URLs.

Data Type Specification: During data loading, you may specify data types for each column if you have this information. This can help in managing memory usage and ensuring data consistency.

Memory Optimization: If the datasets are large, consider using parameters like low_memory=False or dtype in pd.read_csv to optimize memory usage.

Data Dictionary Utilization: Use the data dictionary to understand each column and its data type. This will help in cleaning and transforming the data accurately. Also, it's good to cross-reference the dictionary while loading the data to ensure all columns are correctly interpreted.

Dataframe Inspection: After loading each dataframe, it's good practice to inspect the first few rows using df.head() and check the dataframe's shape and size using df.shape and df.info() to confirm that the data is loaded correctly.

Duplication and Consistency Checks: Perform initial checks for duplicate records or inconsistent data after loading.

Linking Tables: Once the data is loaded and initial inspections are done, you should start linking the tables using primary and foreign keys. This will enable more complex analyses like joining different aspects of the data, which is essential for in-depth analysis.

Dataframe Naming: Ensure dataframe names are descriptive to maintain readability and ease of understanding in your code.

Timestamps and Logging: Your use of a timestamp to log when the import was executed is good practice. You might also want to log other steps in your data processing for better tracking.

Documentation: Document each step of your data loading process. Explain why each step is necessary and how it contributes to your overall analysis.

# Data Overview

In [ ]:
# Display the first few rows of the dataset
print(df.head())

# Get basic info about the dataset
print(df.info())

# Generate summary statistics
print(df.describe())

# Check the dimensions of the DataFrame
print(df.shape)

**The dataset has 41 columns and 1286 rows, with a mix of data types, including integers, floats, booleans, and objects (strings).**

# Data Cleaning:

Before diving into the analysis, The following data cleaning steps will be completed:

* Handle missing values: Identify and handle columns with missing values.
* Data type conversion: Convert columns to appropriate data types.
* Remove unnecessary columns: Drop columns that are not relevant to the analysis.
* Exploratory Data Analysis (EDA): Begin by exploring the data to better understand its characteristics and to identify potential patterns or relationships. This will entail creating visualizations and summary statistics for different columns.

## Handle Missing Values

Check quantity of missing data

In [ ]:
# Create temp DF
missing_data = df.isna().sum()


print(missing_data)

In [ ]:
percentage_missing_data = (missing_data / len(df)) * 100
print(percentage_missing_data)

# Questions

## What are the most common causes of accidents among Part 121 air carriers?

Answering Specific Questions:

For the question about the most common causes of accidents, you can analyze the 'cm_probableCause' column.
For seasonal or time-related patterns, explore the 'cm_eventDate' column and consider creating time-based visualizations.
To understand the evolution of safety records, analyze the 'cm_eventDate' and 'cm_completionStatus' columns over time.
For correlations, consider using correlation matrices and visualizations to identify relationships between factors and accident severity.
Data Visualization: Visualize your findings using libraries like Matplotlib and Seaborn. This will help you communicate your results effectively.

Hypothesis Testing: If your analysis involves hypothesis testing, you can perform statistical tests using libraries such as SciPy.

Documentation: Make sure to document your code and analysis steps clearly in your Jupyter Notebook. This will help you and others understand the analysis process.

Further Analysis: Depending on your findings, you may need to perform more in-depth analyses, such as time series analysis or regression modeling.